test_add_two_negative (class_unittest.class_unittest_one.TestMathMethod) ... ok
test_add_two_one (class_unittest.class_unittest_one.TestMathMethod) ... FAIL
test_add_two_zero (class_unittest.class_unittest_one.TestMathMethod) ... ok

======================================================================
FAIL: test_add_two_one (class_unittest.class_unittest_one.TestMathMethod)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\python_http\class_unittest\class_unittest_one.py", line 10, in test_add_two_one
    self.assertEqual(1, res, '算法错误')
AssertionError: 1 != 2 : 算法错误

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)
